//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaoVat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ADMIN
    {
        public int MAQUANTRI { get; set; }
        [Display(Name = "Tên Đăng Nhập")]
        [Required(ErrorMessage = "Tên tài khoản không được trống")]
        public string TENDANGNHAP { get; set; }
        [Display(Name = "Mật Khẩu")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Mật khẩu không được trống")]
        public string MATKHAU { get; set; }
    }
}
