//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RaoVat.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TINHTHANHPHO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TINHTHANHPHO()
        {
            this.RAOVATs = new HashSet<RAOVAT>();
        }
    
        public int MATHANHPHO { get; set; }
        [Display(Name = "Tỉnh, Thành Phố")]
        public string TENTHANHPHO { get; set; }
        public string LOAITHANHPHO { get; set; }
        public string SLUG { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RAOVAT> RAOVATs { get; set; }
        public List<TINHTHANHPHO> ListTinhThanhPho { get; set; }
    }
}
